CREATE DATABASE OnTapDotNet251121
USE OnTapDotNet251121

CREATE TABLE HETHONG(
		TENDN NVARCHAR(50) NOT NULL PRIMARY KEY, 
		MATKHAU NVARCHAR(50) NOT NULL,
		QUYEN NCHAR(10) NULL
);

INSERT INTO HETHONG VALUES ('admin', '123', '0')

CREATE TABLE HEDAOTAO (
		MAHE char(10) NOT NULL PRIMARY KEY, 
		TENHE char(50) NOT NULL, 
		MUCHP int, 
		SONAM int, 
		GHICHU char(100)
)

INSERT INTO HEDAOTAO VALUES ('He1','He Chinh Quy', 130, 4, 'khong')
INSERT INTO HEDAOTAO VALUES ('He2','He TT & CLC', 130, 4, 'khong')
INSERT INTO HEDAOTAO VALUES ('He3','He Tu Xa', 130, 4, 'khong')

CREATE TABLE KHOAVIEN (
		MAKHOA char(10) NOT NULL PRIMARY KEY, 
		TENKHOA char(50) NOT NULL, 
		DIACHI char(50), 
		SODT char (12)
)

INSERT INTO KHOAVIEN VALUES ('K1', 'CNTT & KTS', '1310 A1 NEU', '0987654321')
INSERT INTO KHOAVIEN VALUES ('K2', 'KHOA 2', '1310 A1 NEU', '0987654321')
INSERT INTO KHOAVIEN VALUES ('K3', 'KHOA 3', '1310 A1 NEU', '0987654321')
INSERT INTO KHOAVIEN VALUES ('K4', 'KHOA 4', '1310 A1 NEU', '0987654321')

CREATE TABLE LOP ( 
		MALOP char(10) NOT NULL PRIMARY KEY, 
		TENLOP char (30), 
		MAKHOA char(10) NOT NULL REFERENCES KHOAVIEN(MAKHOA), 
		CVHT char(30), 
		GHICHU char(100)
)

INSERT INTO LOP VALUES ('CNTT', 'Cong nghe thong tin', 'K1', 'Nguyen Van X', 'khong')
INSERT INTO LOP VALUES ('HTTTQL', 'He Thong', 'K1', 'Nguyen Van X', 'khong')
INSERT INTO LOP VALUES ('KHMT', 'Khoa hoc may tinh', 'K1', 'Nguyen Van X', 'khong')

CREATE TABLE SINHVIEN (
		MASV char(10) NOT NULL PRIMARY KEY, 
		HOTEN char (30) NOT NULL, 
		GIOITINH char(1) NOT NULL, 
		NGAYSINH datetime, 
		NOISINH char (30), 
		MAKHOA char(10) NOT NULL REFERENCES KHOAVIEN(MAKHOA),
		MALOP char(10) NOT NULL REFERENCES LOP(MALOP), 
		MAHE char(10) NOT NULL REFERENCES HEDAOTAO(MAHE)
)

INSERT INTO SINHVIEN VALUES ('SV1', 'Pham Van A', 'M', '2000/12/12', 'HN', 'K1', 'CNTT', 'He1')
INSERT INTO SINHVIEN VALUES ('SV2', 'Pham Thi B', 'F', '2000/12/12', 'HN', 'K1', 'KHMT', 'He1')
INSERT INTO SINHVIEN VALUES ('SV3', 'Pham Thi C', 'F', '2000/12/12', 'HN', 'K1', 'CNTT', 'He1')
INSERT INTO SINHVIEN VALUES ('SV4', 'Pham Van D', 'M', '2000/12/12', 'HN', 'K1', 'HTTTQL', 'He1')
INSERT INTO SINHVIEN VALUES ('SV5', 'Pham Thi E', 'F', '2000/12/12', 'HN', 'K1', 'CNTT', 'He1')

GO
CREATE VIEW view_SV_TheoLop
AS
SELECT*FROM SINHVIEN WHERE MALOP = 'CNTT'

SELECT*FROM view_SV_TheoLop